<form action="" method="post">
    <div class="form-group">
        <label for="bezeichnung">Bezeichnung</label>
        <input type="text" class="form-control" id="bezeichnung" placeholder="Bezeichnung">
        <p class="help-block">Hier wird die Bezeichnung für die Bestellung festgelegt.</p>
    </div>
    <div class="form-group">
        <label for="material">Material</label>
        <select id="material" class="form-control">
            <?php
            /* @var $material \Application\Entity\Material */
            foreach($this->materialien as $material) { ?>
            <option value="<?php echo $material->getId() ?>"><?php echo $material->getBezeichnung(). ' ('. $material->getPreis() .' EUR)' ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="form-group">
        <label for="anzahl">Anzahl</label>
        <input type="text" class="form-control" id="anzahl">
        <p class="help-block">Wieviel brauchen Sie denn davon?</p>
    </div>

    <button type="submit" class="btn btn-default">Bestellen</button>
</form>
