<?php

// Append Chart.js und underscore.js library
$this->headScript()->appendFile($this->basePath('js/libs/Chart.js'))
                   ->appendFile($this->basePath('js/libs/underscore.js'));
?>
<canvas id="chart"></canvas>
<script type="application/javascript">

    // Report Daten
    var data = <?php echo json_encode($this->data); ?>;

    // Canvas kontext laden
    var ctx = document.getElementById("chart");

    //
    var dataLabels = <?php echo json_encode(array_keys($this->data)); ?>;
    var dataValues = <?php echo json_encode(array_values($this->data)); ?>;

    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: <?php echo json_encode(array_keys($this->data)); ?>,
            datasets: [{
                label: '# of Votes',
                data: <?php echo json_encode(array_values($this->data)); ?>,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero:true
                    }
                }]
            }
        }
    });

</script>
