<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Bestellen</h3>
            </div>
            <div class="panel-body">
                <p>Eingabeformular für neue Bestellungen.</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('application/wildcard', array('controller' => 'Bestellung', 'action' => 'bestellen')); ?>">Hier weiter &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Alle Bestellungen</h3>
            </div>
            <div class="panel-body">
                <p>Übersicht aller Bestellung und Funktion um diese zu genehmigen.</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('application/wildcard', array('controller' => 'Bestellung', 'action' => 'uebersicht')); ?>">Hier weiter &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Report</h3>
            </div>
            <div class="panel-body">
                <p>Report für die Geschäftsleitung.</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('application/wildcard', array('controller' => 'Report', 'action' => 'bestellungen-pro-kalenderwochen')); ?>">Hier weiter &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
